# Generated by Django 5.0.2 on 2024-02-14 18:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="modified")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=100, verbose_name="full name")),
                ("birth_date", models.DateField(blank=True, null=True, verbose_name="birth date")),
            ],
            options={
                "verbose_name": "client",
                "verbose_name_plural": "clients",
                "db_table": 'public"."clients',
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="modified")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=100, verbose_name="full name")),
                ("birth_date", models.DateField(blank=True, null=True, verbose_name="birth date")),
            ],
            options={
                "verbose_name": "employee",
                "verbose_name_plural": "employees",
                "db_table": 'public"."employees',
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="modified")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("quantity", models.IntegerField(default=1, verbose_name="quantity")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name="price"),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "db_table": 'public"."products',
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="created")),
                ("modified", models.DateTimeField(auto_now=True, verbose_name="modified")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="total price")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="orders", to="med.client"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="orders", to="med.employee"
                    ),
                ),
                ("products", models.ManyToManyField(blank=True, to="med.product")),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "db_table": 'public"."orders',
            },
        ),
    ]
